# Generated by Django 5.1.4 on 2026-08-12 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('notes', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_deleted'], name='notes_note_user_id_727199_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_archived'], name='notes_note_user_id_d0efd6_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_favorite'], name='notes_note_user_id_033aa6_idx'),
        ),
    ]
